
/**
 * This code was generated by
 * [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "NUISwitchSpec.h"

namespace facebook {
namespace react {

static facebook::jsi::Value
__hostFunction_NativeNUISwitchModuleSpecJSI_install(
    facebook::jsi::Runtime &rt, TurboModule &turboModule,
    const facebook::jsi::Value *args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule)
      .invokeJavaMethod(rt, BooleanKind, "install", "()Z", args, count,
                        cachedMethodId);
}

NativeNUISwitchModuleSpecJSI::NativeNUISwitchModuleSpecJSI(
    const JavaTurboModule::InitParams &params)
    : JavaTurboModule(params) {
  methodMap_["install"] =
      MethodMetadata{0, __hostFunction_NativeNUISwitchModuleSpecJSI_install};
}

std::shared_ptr<TurboModule>
NUISwitchSpec_ModuleProvider(const std::string &moduleName,
                                  const JavaTurboModule::InitParams &params) {
  if (moduleName == "SwitchViewModule") {
    return std::make_shared<NativeNUISwitchModuleSpecJSI>(params);
  }
  return nullptr;
}

} // namespace react
} // namespace facebook
